# Generated by Django 4.1.7 on 2025-12-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_appointmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='consultationfee',
            field=models.CharField(max_length=100),
        ),
    ]
